name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of YOLOv8 Vehicle Annotator are you running?
      placeholder: e.g., v2.0.0
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 10
        - Windows 11
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Ubuntu 20.04
        - Ubuntu 22.04
        - Other Linux
    validations:
      required: true
      
  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      options:
        - Python 3.8
        - Python 3.9
        - Python 3.10
        - Python 3.11
        - Python 3.12
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      
  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell
      
  - type: dropdown
    id: ai-feature
    attributes:
      label: AI Feature Related
      description: Is this bug related to AI functionality?
      options:
        - "Yes"
        - "No"
        - "Not sure"
        
  - type: checkboxes
    id: gpu
    attributes:
      label: GPU Information
      description: If AI-related, please check your GPU setup
      options:
        - label: NVIDIA GPU available
        - label: CUDA installed
        - label: Using CPU-only mode
        
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as system specifications, environment setup, etc.
      
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Before submitting, please confirm
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have included all relevant information
          required: true
        - label: I can reproduce this issue consistently
          required: true
