blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion Forum
    url: https://github.com/ericchen2023/yolo-vehicle-annotator/discussions
    about: Ask questions and discuss features with the community
  - name: 📚 Documentation
    url: https://github.com/ericchen2023/yolo-vehicle-annotator#readme
    about: Check our comprehensive documentation and guides
  - name: 🔧 Installation Help
    url: https://github.com/ericchen2023/yolo-vehicle-annotator/wiki/Installation-Guide
    about: Get help with installation and setup issues
