name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! 💡
        
  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - UI/UX Improvement
        - AI/ML Enhancement
        - Performance Optimization
        - Export/Import Feature
        - Annotation Tool
        - Project Management
        - Integration
        - Other
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my work)
        - High (would significantly improve my workflow)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true
      
  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (minor UI change or setting)
        - Medium (new dialog or tool)
        - Complex (major feature or integration)
        - Very Complex (requires significant architecture changes)
        - Not sure
        
  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be helpful.
      placeholder: |
        1. When annotating large datasets...
        2. For users who need to...
        3. In workflows where...
        
  - type: textarea
    id: mockup
    attributes:
      label: UI Mockup or Workflow
      description: If applicable, describe how you envision the user interface or workflow for this feature.
      
  - type: checkboxes
    id: related-features
    attributes:
      label: Related Features
      description: Which existing features would this enhancement relate to?
      options:
        - label: Annotation tools
        - label: AI/ML functionality
        - label: Export/Import
        - label: Project management
        - label: Performance
        - label: UI/UX
        - label: Keyboard shortcuts
        - label: File handling
        
  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: If you have technical knowledge, please share any implementation details or suggestions.
      
  - type: dropdown
    id: contribution
    attributes:
      label: Contribution Interest
      description: Would you be interested in contributing to the implementation of this feature?
      options:
        - "Yes, I can implement this"
        - "Yes, I can help with testing"
        - "Yes, I can help with documentation"
        - "Maybe, depending on complexity"
        - "No, but I'd love to see it implemented"
        
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
      
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Before submitting, please confirm
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have clearly described the problem and proposed solution
          required: true
        - label: This feature would benefit other users, not just my specific use case
          required: true
